# Generated by Django 4.2.4 on 2023-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestLog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("small_post", models.TextField(max_length=1000)),
                ("pubdate", models.DateTimeField(verbose_name="date published")),
            ],
            options={"ordering": ["-pubdate"],},
        ),
    ]
