# Generated by Django 4.2.4 on 2023-08-26 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("guestLog", "0002_smallpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinglePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this particular post across whole library",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_text", models.TextField(max_length=1000)),
                ("pubdate", models.DateTimeField(verbose_name="date published")),
            ],
            options={"ordering": ["-pubdate"],},
        ),
        migrations.DeleteModel(name="SmallPost",),
    ]
