# Generated by Django 4.0.5 on 2022-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbPractice', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathproblem',
            name='the_problem',
            field=models.CharField(max_length=100),
        ),
    ]
