# Generated by Django 4.0.5 on 2022-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_author_book_genre_bookinstance_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
            ],
        ),
    ]
